name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - name: Configure
        run: |
          cp "configurations/Release.xcconfig" "Telegram-Mac/Release.xcconfig"
          sh scripts/configure_frameworks.sh
      - name: Build
        run: |
          export FASTLANE_XCODE_LIST_TIMEOUT=120
          fastlane Release
      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: "artifacts"
          path: ./output
